//! Fixed tables for every finite BF16 input, generated by the same backend.
//! Query input/state is never retained. Non-BF16/nonfinite inputs use originals.
use std::cell::RefCell;
const N:usize=65536;
struct Tables {values:[Box<[f32;N]>;4]}
thread_local! {static FIXED:RefCell<Option<Tables>>=const{RefCell::new(None)};}
pub fn prepare()->usize {
 FIXED.with(|t| {let mut t=t.borrow_mut();if t.is_none() {
  let mut values:[Box<[f32;N]>;4]=core::array::from_fn(|_|vec![0.;N].into_boxed_slice().try_into().unwrap());
  for i in 0..N {let x=f32::from_bits((i as u32)<<16);if x.is_finite() {values[0][i]=original::<0>(x);values[1][i]=original::<1>(x);values[2][i]=original::<2>(x);values[3][i]=original::<3>(x);}}
  *t=Some(Tables{values});}4*N*4})
}
pub fn bytes()->usize {FIXED.with(|t|if t.borrow().is_some(){4*N*4}else{0})}
pub fn clear(){FIXED.with(|t|*t.borrow_mut()=None);}
#[inline]
pub fn lookup<const K:usize>(x:f32)->Option<f32> {
 const{assert!(K<4);}
 let bits=x.to_bits();if bits&65535!=0 || bits&0x7f800000==0x7f800000 {return None;}
 FIXED.with(|t|t.borrow().as_ref().map(|t|t.values[K][(bits>>16)as usize]))
}
#[inline]
pub fn original<const K:usize>(x:f32)->f32 {const{assert!(K<4);}match K {0=>crate::bf_sigmoid_original(x),1=>crate::bf_silu_original(x),2=>crate::bf_softplus_original(x),3=>crate::silu_original(x),_=>unreachable!()}}
#[inline]
pub fn optimized<const K:usize>(x:f32)->f32 {const{assert!(K<4);}match K {0=>crate::bf_sigmoid(x),1=>crate::bf_silu(x),2=>crate::bf_softplus(x),3=>crate::silu(x),_=>unreachable!()}}
#[cfg(test)] mod tests {use super::*;
 #[test] fn exhaustive_bf16_and_fallback_bits(){clear();assert_eq!(bytes(),0);assert!(lookup::<0>(1.).is_none());assert_eq!(prepare(),1_048_576);assert_eq!(prepare(),1_048_576);
  for i in 0..N {let x=f32::from_bits((i as u32)<<16);if x.is_finite(){assert_eq!(original::<0>(x).to_bits(),optimized::<0>(x).to_bits());assert_eq!(original::<1>(x).to_bits(),optimized::<1>(x).to_bits());assert_eq!(original::<2>(x).to_bits(),optimized::<2>(x).to_bits());assert_eq!(original::<3>(x).to_bits(),optimized::<3>(x).to_bits());}}
  for bits in [0x3f800001,0xbf800001,1,0x80000001,0x7f800000,0xff800000,0x7fc10000,0xffc10000] {let x=f32::from_bits(bits);assert!(lookup::<0>(x).is_none());assert_eq!(original::<0>(x).to_bits(),optimized::<0>(x).to_bits());assert_eq!(original::<1>(x).to_bits(),optimized::<1>(x).to_bits());assert_eq!(original::<2>(x).to_bits(),optimized::<2>(x).to_bits());assert_eq!(original::<3>(x).to_bits(),optimized::<3>(x).to_bits());}clear();assert_eq!(bytes(),0);
 }
}
