#!/usr/bin/env python3
"""Generate constant-index SIMD code from the block256 dot-product specification.

Keep expanded weights in Wasm locals instead of an indexed temporary array. The
integer reduction is balanced; F32 operations preserve the public numeric order.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def dot(column):
    parts = [f'i32x4_dot_i16x8(x{i}, w{column}_{i})' for i in range(32)]
    while len(parts)>1:
        parts = [f'i32x4_add({parts[i]}, {parts[i+1]})' for i in range(0,len(parts),2)]
    return parts[0]

def generate():
    lines = ['//! Generated by scripts/generate_int8_tile.py; edit the specification there.',
             '//! Signed block256 dots fit I32: abs(sum) <= 256*127*128.',
             '//! Integer reassociation is exact. F32 scales/addition keep block order.',
             'use core::arch::wasm32::*;',
             ]
    lines += ['#[target_feature(enable="simd128")]',
              'pub(super) unsafe fn accumulate<const R: usize>(q: *const i16, w: *const i8, cols: usize, start: usize, sx: *const f32, stride: usize, sw: *const f32, out: &mut [[f32; 8]; R]) {']
    for c in range(8):
        lines.append(f'    let row{c} = w.add({c} * cols + start);')
        lines += [f'    let w{c}_{i} = i16x8_extend_low_i8x16(v128_load64_zero(row{c}.add({i*8}).cast()));' for i in range(32)]
    lines += [f'    let scale{c} = v128_load(sw.add({c}).cast());' for c in (0,4)]
    lines += ['    for token in 0..R {','        let input = q.add(token * cols + start);']
    lines += [f'        let x{i} = v128_load(input.add({i*8}).cast());' for i in range(32)]
    lines.append('        let activation = f32x4_splat(*sx.add(token * stride));')
    for c in range(8):
        lines.append(f'        let d{c} = {dot(c)};')
        if c%4==3:
            first=c-3
            lines += [f'        let left = i32x4_add(i32x4_shuffle::<0,2,4,6>(d{first},d{first+1}),i32x4_shuffle::<1,3,5,7>(d{first},d{first+1}));',
                      f'        let right = i32x4_add(i32x4_shuffle::<0,2,4,6>(d{first+2},d{c}),i32x4_shuffle::<1,3,5,7>(d{first+2},d{c}));',
                      '        let integer = i32x4_add(i32x4_shuffle::<0,2,4,6>(left,right),i32x4_shuffle::<1,3,5,7>(left,right));',
                      f'        let output = out.as_mut_ptr().cast::<f32>().add(token * 8 + {first});',
                      f'        let scaled = f32x4_mul(f32x4_mul(f32x4_convert_i32x4(integer),activation),scale{first});',
                      '        v128_store(output.cast(),f32x4_add(v128_load(output.cast()),scaled));']
    lines += ['    }','}']
    return '\n'.join(lines)+'\n'

if __name__=='__main__':
    (ROOT/'crates/imajev-runtime/src/int8_tile.rs').write_text(generate())
