#!/usr/bin/env python3
"""Exact I8 products, fixed-weight-bounded I16 windows, original F32 order."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def tree(xs,op):
 if len(xs)==1:return xs[0]
 mid=len(xs)//2;return f'{op}({tree(xs[:mid],op)},{tree(xs[mid:],op)})'
def dot(window):
 terms=[]
 for start in range(0,32,window//8):
  halves=[]
  for side in ['low','high']:
   prods=[f'i16x8_extmul_{side}_i8x16($input[{k}],weights[$j][{k}])' for k in range(start,start+window//8)]
   halves.append(f'i32x4_dot_i16x8({tree(prods,"i16x8_add")},ones)')
  terms.append(tree(halves,'i32x4_add'))
 return tree(terms,'i32x4_add')
s='''//! Generated by scripts/generate_bounded_i16.py. Private validated spans.
//! W16 is safe for all I8 weights: 127*(128+128)=32512.
//! W32 uses the proof mode fixed during prepare, never scans weights in query.
#[target_feature(enable="simd128")]
pub(crate) unsafe fn accumulate(q:*const i8,w:*const i8,cols:usize,start:usize,sx:*const f32,stride:usize,sw:*const f32,modes:*const u8,sums:&mut[[f32;32]]) {
 debug_assert!(sums.len()<=48);use core::arch::wasm32::*;
 let ones=i16x8_splat(1);
 let ws:[v128;8]=core::array::from_fn(|j|v128_load(sw.add(j*4).cast()));
 let mut weights=[[i32x4_splat(0);32];16];
 let mut safe=[false;16];
 macro_rules! pair {($j:literal)=>{{
  let p=w.add(($j as usize).wrapping_mul(cols).wrapping_mul(2).wrapping_add(start.wrapping_mul(2)));
  weights[$j]=['''+','.join(f'v128_load(p.add({i*16}).cast())' for i in range(32))+'''];
  safe[$j]=*modes.add(($j as usize).wrapping_mul(stride))!=0;
 }}}
 '''+''.join(f'pair!({i});' for i in range(16))+'''
 macro_rules! dot {($j:literal,$input:ident)=>{{if safe[$j] {'''+dot(32)+'''}else{'''+dot(16)+'''}}}}
 macro_rules! group {($i:expr,$input:ident,$j:literal,$a:literal,$b:literal)=>{{
 let a=dot!($a,$input);let b=dot!($b,$input);
 let packed=i32x4_shuffle::<0,2,4,6>(a,b);let rest=i32x4_shuffle::<1,3,5,7>(a,b);
 let total=i32x4_add(packed,rest);
 let scaled=f32x4_mul(f32x4_mul(f32x4_convert_i32x4(total),f32x4_splat(*sx.add(($i as usize).wrapping_mul(stride)))),ws[$j/4]);
 let dst=sums[$i].as_mut_ptr().add($j);v128_store(dst.cast(),f32x4_add(v128_load(dst.cast()),scaled));
 }}}
 for i in 0..sums.len() {
 let row=q.add(i.wrapping_mul(cols).wrapping_add(start).wrapping_mul(2));
 let input=['''+','.join(f'v128_load(row.add({i*16}).cast())' for i in range(32))+'''];
 '''+''.join(f'group!(i,input,{i*4},{i*2},{i*2+1});' for i in range(8))+'''
 }
}
'''
p=ROOT/'scripts/bounded_i16_bench/src/kernel.rs'
if not p.exists() or p.read_text()!=s:p.write_text(s)
