#!/usr/bin/env python3
"""Keep numerical drift, typed validity, diagnostic judgments and query costs separate."""
import collections,hashlib,json,pathlib
import numpy as np
ROOT=pathlib.Path(__file__).resolve().parents[1]
new=json.loads((ROOT/'artifacts/integer-full-617/first-report.json').read_text());old=json.loads((ROOT/'artifacts/multi-token-compact-lossless-v2-617/first-report.json').read_text());a=new['decision_query']['ok']['decision'];b=old['decision_query']['ok']['decision'];assert new['pack_hash']==old['pack_hash'] and new['input_hash']==old['input_hash']
r={k:v for k,v in new.items() if k!='queries'};r['query_metrics']=[dict(index=q['index'],op=q['op'],tensor=q['tensor'],**q['ok'],wall_seconds=q['wall_seconds']) for q in new['queries']]
r['arithmetic_comparison']=dict(scope='Same INT8 weights and lossless wire; added per-token block256 activation quantization inside base projection and integer reduction/scaling; LoRA input remains original F32',before_queries=old['query_count'],after_queries=new['query_count'],before_instructions=old['total_instructions'],after_instructions=new['total_instructions'],instruction_reduction=1-new['total_instructions']/old['total_instructions'],before_bytes=old['total_candid_bytes'],after_bytes=new['total_candid_bytes'],before_seconds=old['wall_seconds_this_run'],after_seconds=new['wall_seconds_this_run'],same_choice=a['value']==b['value'],max_logit_error=float(abs(np.asarray(a['raw_logits'])-b['raw_logits']).max()),max_probability_error=float(abs(np.asarray(a['probabilities'])-b['probabilities']).max()),unknown_error=abs(a['unknown_probability']-b['unknown_probability']),bitwise_equal=False)
r['layer_errors']=[]
for layer in range(32):
 x=np.load(ROOT/f'artifacts/integer-full-617/queries/layer-{layer:02d}.npy');y=np.load(ROOT/f'artifacts/multi-token-compact-lossless-v2-617/queries/layer-{layer:02d}.npy');r['layer_errors'].append(dict(layer=layer,max_error=float(abs(x-y).max()),mean_error=float(abs(x-y).mean()),bitwise_equal=bool(np.array_equal(x.view(np.uint32),y.view(np.uint32)))))
r['target_50_queries_achieved']=new['query_count']<=50;r['query_budget_only_minimum_at_measured_total']=(new['total_instructions']+4_999_999_999)//5_000_000_000;r['source_report_sha256']=hashlib.sha256((ROOT/'artifacts/integer-full-617/first-report.json').read_bytes()).hexdigest();(ROOT/'docs/integer-full-results.json').write_text(json.dumps(r,indent=2)+'\n')
integer=json.loads((ROOT/'artifacts/host-integer-orders-pinned-embedding.json').read_text());f32=json.loads((ROOT/'artifacts/host-pack-f32-orders-pinned-embedding.json').read_text());official=json.loads((ROOT/'artifacts/reference-orders.json').read_text());assert integer['weight_pack_hash']==f32['weight_pack_hash']==integer['embedding_pack_hash']==f32['embedding_pack_hash']==new['pack_hash']
assert len(integer['records'])==len(f32['records'])==len(official['records'])==23
records=[];groups=collections.defaultdict(list)
for i,(x,y,z) in enumerate(zip(integer['records'],f32['records'],official['records'])):
 assert x['id']==y['id']==z['id'] and x['offset']==y['offset']==z['offset'] and x['input_sha256']==y['input_sha256']==z['input_sha256']
 value=x['result']['value'];gold=x['gold'];scores=x['result']['scores'];before=y['result']['scores'];record=dict(index=i,id=x['id'],offset=x['offset'],gold=gold,integer_value=value,pack_f32_value=y['result']['value'],official_value=z['result']['value'],integer_matches_pack_f32_label=value==y['result']['value'],integer_matches_official_label=value==z['result']['value'],correct=None if gold is None else value==(None if gold=='__unknown__' else gold),typed_output_valid=value is None or value in x['options'],max_probability_drift_vs_same_pack_f32=max(abs(scores[k]-before[k]) for k in scores),unknown_drift_vs_same_pack_f32=abs(scores['__unknown__']-before['__unknown__']),integer_scores=scores,pack_f32_scores=before);records.append(record);groups[x['id']].append(record)
evaluation=dict(scope='23 host forwards, 10 underlying diagnostic questions, cyclic orders separately at rotations=1; not a representative labeled benchmark; host/Wasm nonlinear differences remain',model=integer['model_lock_sha256'],pack_hash=integer['weight_pack_hash'],embedding_pack_hash=integer['embedding_pack_hash'],embedding_precision=integer['embedding_precision'],historical_embedding_note='Reports without the pinned-embedding suffix used official BF16 embedding; excluded from this same-pack comparison',integer_matches_pack_f32_labels=sum(r['integer_matches_pack_f32_label'] for r in records),integer_matches_official_labels=sum(r['integer_matches_official_label'] for r in records),total_records=len(records),labeled_records=sum(r['gold'] is not None for r in records),correct_integer_labeled_records=sum(r['correct'] is True for r in records),labeled_questions=sum(v[0]['gold'] is not None for v in groups.values()),correct_integer_labeled_questions_in_original_order=sum(v[0]['correct'] is True for v in groups.values()),all_typed_outputs_valid=all(r['typed_output_valid'] for r in records),max_probability_drift_vs_same_pack_f32=max(r['max_probability_drift_vs_same_pack_f32'] for r in records),option_order_dependence=[k for k,v in groups.items() if len({r['integer_value'] for r in v})>1],records=records,report_hashes={p:hashlib.sha256((ROOT/'artifacts'/p).read_bytes()).hexdigest() for p in ['host-integer-orders-pinned-embedding.json','host-pack-f32-orders-pinned-embedding.json','reference-orders.json']})
(ROOT/'docs/integer-judgments.json').write_text(json.dumps(evaluation,indent=2)+'\n');print(r['arithmetic_comparison']);print({k:v for k,v in evaluation.items() if k not in ('records','report_hashes')})
