[package]
name = "runtime-kernel-bench"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[features]
local-ic = []

[lib]
crate-type = ["cdylib"]

[dependencies]
imajev-runtime = { path = "../../crates/imajev-runtime", features = ["experimental-single-quad", "experimental-strassen-output128"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
overflow-checks = true
